apiVersion: v1
kind: Service
metadata:
  name: edgex-app-service-configurable-rules
spec:
  type: ClusterIP
  selector:
    app: edgex-app-service-configurable-rules
  ports:
    - port: 48100
      name: port-48100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-app-service-configurable-rules
  labels:
    app: edgex-app-service-configurable-rules
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgex-app-service-configurable-rules
  template:
    metadata:
      name: edgex-app-service-configurable-rules
      labels:
        app: edgex-app-service-configurable-rules
    spec:
      containers:
        - name: edgex-app-service-configurable-rules
          image: edgexfoundry/docker-app-service-configurable:1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 48100
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: 48100
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: 48100
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edgex-app-service-configurable-rules
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: distro.k8s
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: edgex-app-service-configurable-rules
              servicePort: 48100
